apiVersion: v1
kind: Service
metadata:
  name: cryptchat-service
spec:
  selector:
    app: cryptchat
  type: LoadBalancer
  ports:
    - name: cryptchat-http
      protocol: TCP
      port: 3000          # internal cluster port
      targetPort: 3000    # container port
